server:
  port: 8090
spring:
  datasource:
    password: $elsyN123
    url: jdbc:mysql://localhost:3306/dbLoja?createDatabaseIfNotExist=true
    username: root
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
